apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library.fullname" . }}-config
data:
  spring.profiles.active: dev,admin
  spring.datasource.url: 'jdbc:postgresql://postgres-postgresql/library'