debug: true

library:
  size: ${random.int(2,10)}

spring:
  freemarker:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  main:
    lazy-initialization: true
    banner-mode: off