# configure auto-configured MultipartConfigElement

spring:
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
      location: ${java.io.tmpdir}

logging:
  level.: debug

com:
  justgifit:
    optimize: true
    gif-location: ${java.io.tmpdir}/gif
