
### GET book by author name
GET localhost:8080/books?author=Who cares?

### POST new expert
POST localhost:8080/experts
Content-Type: application/json

{
  "name": "Denis",
  "contact": "+380684457044",
  "recommendations": [
    {
      "sentence": "Hibernate in Action by Who cares?"
    },
    {
      "sentence": "Designing Data-Intensive Applications by Martin Kleppmann"
    }
  ]
}

###
POST localhost:8080/experts
Content-Type: application/json

{
  "name": "Mytrofan",
  "contact": "+380934457044",
  "recommendations": [
    {
      "sentence": "Spring in Action by Who knows?"
    },
    {
      "sentence": "Effective Java by Josua Bloch"
    }
  ]
}


