kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boot-admin-discoverer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]