apiVersion: v1
kind: Service
metadata:
  name: boot-admin
  labels:
    app: boot-admin
    tech-stack: springboot
spec:
  selector:
    app: boot-admin
  ports:
    - port: 8081
#  type: NodePort
  type: ClusterIP
