apiVersion: v2
name: library
description: A Helm chart for library application

type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: ingress-nginx
    version: ">=4.0.18, <5.0.0"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled
