# Default values for library.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: hub.docker.com
  name: lelyak/library
  version: 0.1.0
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  port: 8080
  startup:
    waitSeconds: 30
  liveness:
    path: /admin/health/liveness
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /admin/health/readiness
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3

ingress-nginx:
  controller:
    ingressClass: nginx
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: 127.0.0.1

ingress:
  enabled: false
  host: localhost
  limitConnections: 10
  limitRps: 1

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 800m
    memory: 1024Mi





#serviceAccount:
#  # Specifies whether a service account should be created
#  create: true
#  # Annotations to add to the service account
#  annotations: {}
#  # The name of the service account to use.
#  # If not set and create is true, a name is generated using the fullname template
#  name: ""

#podAnnotations: {}

#podSecurityContext: {}
  # fsGroup: 2000

#securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local

#resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

#nodeSelector: {}

#tolerations: []

#affinity: {}
